User.create!(name: "Dirk Diggler", email: "dirk@example.com", balance: 10, password: "password")
User.create!(name: "Reed Rothchild", email: "reed@example.com", balance: 450, password: "password")
User.create!(name: "Amber Waves", email: "amber@example.com", balance: 100, password: "password")

Contest.create!(date: "05/17/2020", game: "High Temp", win: "-110", line: 65, real_temp: 68)
Contest.create!(date: "05/18/2020", game: "High Temp", win: "-110", line: 66, real_temp: 67)
Contest.create!(date: "05/19/2020", game: "High Temp", win: "-110", line: 65, real_temp: 53)
Contest.create!(date: "05/20/2020", game: "High Temp", win: "-110", line: 66, real_temp: "")
Contest.create!(date: "05/21/2020", game: "High Temp", win: "-110", line: 60, real_temp: "")
Contest.create!(date: "05/22/2020", game: "High Temp", win: "-110", line: 62, real_temp: "")
Contest.create!(date: "05/23/2020", game: "High Temp", win: "-110", line: 75, real_temp: "")
Contest.create!(date: "05/24/2020", game: "High Temp", win: "-110", line: 82, real_temp: "")
Contest.create!(date: "05/25/2020", game: "High Temp", win: "-110", line: 77, real_temp: "")
Contest.create!(date: "05/26/2020", game: "High Temp", win: "-110", line: 75, real_temp: "")
Contest.create!(date: "05/27/2020", game: "High Temp", win: "-110", line: 80, real_temp: "")
Contest.create!(date: "05/28/2020", game: "High Temp", win: "-110", line: 79, real_temp: "")

Bet.create!(contest_id: 1, user_id: 1, amount: 10, status: "lose", pick: "under")
Bet.create!(contest_id: 2, user_id: 1, amount: 20, status: "lose", pick: "under")
Bet.create!(contest_id: 3, user_id: 1, amount: 40, status: "lose", pick: "over")
Bet.create!(contest_id: 4, user_id: 1, amount: 80, status: "pending", pick: "over")
Bet.create!(contest_id: 5, user_id: 1, amount: 160, status: "pending", pick: "over")
Bet.create!(contest_id: 6, user_id: 1, amount: 320, status: "pending", pick: "over")
Bet.create!(contest_id: 1, user_id: 2, amount: 20, status: "win", pick: "over")
Bet.create!(contest_id: 3, user_id: 2, amount: 50, status: "win", pick: "under")
Bet.create!(contest_id: 5, user_id: 2, amount: 10, status: "pending", pick: "under")
Bet.create!(contest_id: 6, user_id: 2, amount: 70, status: "pending", pick: "over")
